### ISSUE TITLE
希望有打通类似server酱之类的第三方通知

### ISSUE THREAD

**Issue by mm519897405** [Qliangw/emby_notify#1]
RT

**Comment by Qliangw** [comment]
> RT

可以添加对`server酱`、`pushplus`、`bark`等通知的支持（不过个人时间有限可能没有那么快更

**Comment by mm519897405** [comment]
> > RT
> 
> 可以添加对`server酱`、`pushplus`、`bark`等通知的支持（不过个人时间有限可能没有那么快更

感谢，持续关注中，已经邀请小圈子关注了

**Comment by Qliangw** [comment]
> RT

我看了下server酱官网，免费用户每天只有五条，不太够用吧（还是我没有找到正确的地方
