### ISSUE TITLE
不能顯示TMDB簡介

### ISSUE THREAD

**Issue by brucetangian** [Qliangw/emby_notify#3]
有關電影入庫通知，不能顯示tmbd 簡介，已填入API Key 。

**Comment by Qliangw** [comment]
能不能贴个图看一下通知状态

**Comment by Qliangw** [comment]
> 有關電影入庫通知，不能顯示tmbd 簡介，已填入API Key 。

大概了解问题了

- api填写错误（确认一下api_key是否能正常使用）
- emby的网络不能访问tmdb（修改host可解决）
