### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by yangchris4** [Qliangw/emby_notify#5]
1.入库通知背景 可以联动radarr & sonarr 下的/meida/cover 文件吗 ？  这样看上去相关性更强一点（花里胡哨的）。
![test](https://user-images.githubusercontent.com/13220804/161489921-73d63ede-821f-44e7-b094-5ba539cbc029.png)

2.虽然对我来说影响不大，但是UTC和GMT时间问题 可能让一部份强迫症难受。

**Comment by Qliangw** [comment]
1. xarr家族停用了，不适用我看老剧和国漫的习惯，再一个我是PLEX用户，emby是群友们催逼着搞的，大概率不想增加这个
2. 关于时间，docker的话添加一个环境变量的参数即可：`TZ=CST-8`
