### ISSUE TITLE
测试正常，实际播放报错

### ISSUE THREAD

**Issue by M-chacha** [Qliangw/emby_notify#6]
仅配置了播放通知进行测试，使用sh notify.sh test 测试能正常推送到企微，实际在emby播放时即报错。
/config/plugins/emby_notify/notify.sh: 29: Syntax error: "(" unexpected
宿主机为unraid6.9.2系统，硬件架构为x86。

**Comment by mymoonyue** [comment]
同样报错，请问老哥解决了吗
